@startuml Communaute
class Utilisateur {
    id : Integer
    email : String
    pseudo : String
    'SHA256 du mot de passe
    mot_de_passe : char[32]
    'Par exemple : "Europe/Paris", https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    timezone : String
    /'Rangs qui définit les droits des utilisateurs
        "A" : administrateur
        "E" : peut valider une espèce
        "L" : peut valider un lien
        "M" : peut valider un media
    '/
    rang : String
    ' Clé API au format GUID (https://fr.wikipedia.org/wiki/Globally_Unique_Identifier)
    api_key : char[16]
    'OAuth, les token ont des tailles variables
    'Twitter semble limiter à 50 charactères
    facebook_profile_id : Integer
    facebook_token : String
    twitter_profile_id : Integer
    twitter_token : String
    google_profile_id : Integer
    google_token : String
    github_profile_id : Integer
    github_token : String
}
class Potager {
    id : Integer
    nom : String
    /'coordonnées GPS + altitude ==> format à définir
      Pourrait être utile pour un futur service connecté à la météo (pluviométrie, ensoleillement, températures pour éviter gel, ...)
    '/
    geolocalisation : String
    'Si le potager est partagé avec les autres utilisateurs
    public : bool
}
class Media {
    'hash est une valeur unique (on évite les doublons en base de données)
    hash : String
    url : String
    /'
        P = photo
        R = référence
        L = lien
        V = vidéo
        B = boutique, c.a.d. où trouver le produit
    '/
    type : char
}
class Graph {
    id : Integer
    nom : String
}
class Modification {
    id : Integer
    quand : datetime
    'E = Espèce, M = Média, L = Lien
    quoi : char
    'ID de l'espèce/média/lien
    element : Integer
    'les champs suivants prennent les ID des utilisateurs
    qui : Integer
    approuver_par : Integer
    'C = création, M = modification, S = suppression
    action : char
    'associations clé-valeur au format JSON (ex : {"feuillage":"C", "ph":"N"} )
    anciennes_valeurs : String
}
' Relations
Potager "0..1" -- "*" Media
Utilisateur "1" -- "*" Potager : MesPotagers
Utilisateur "*" -- "*" Plante : MesPlantesFavorites
Utilisateur "1" -- "*" Graph : MesInteractions
Graph "*" -- "*" Plante
@enduml