"""empty message

Revision ID: 19a7d22c00f1
Revises: 
Create Date: 2020-01-14 23:57:41.660891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a7d22c00f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('interaction', sa.String(), nullable=True),
    sa.Column('references', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('wiki', sa.String(), nullable=True),
    sa.Column('taxonomy', sa.String(), nullable=True),
    sa.Column('latin_name', sa.String(), nullable=True),
    sa.Column('TaxID', sa.Integer(), nullable=True),
    sa.Column('NCBI', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species')
    op.drop_table('interactions')
    # ### end Alembic commands ###
