"""empty message

Revision ID: 484d99406a64
Revises: 19a7d22c00f1
Create Date: 2020-01-15 10:30:10.898398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484d99406a64'
down_revision = '19a7d22c00f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interactions', 'interaction',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interactions', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interactions', 'target',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('source_target', 'interactions', ['source', 'target'])
    op.alter_column('species', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('species', 'common_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'species', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'species', type_='unique')
    op.alter_column('species', 'common_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('species', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('source_target', 'interactions', type_='unique')
    op.alter_column('interactions', 'target',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('interactions', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('interactions', 'interaction',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
