"""empty message

Revision ID: 9fd355c0ac64
Revises: 484d99406a64
Create Date: 2020-01-15 17:02:27.255465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd355c0ac64'
down_revision = '484d99406a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('source_target', 'interactions', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('source_target', 'interactions', ['source', 'target'])
    # ### end Alembic commands ###
